### ISSUE TITLE
Error: unsupported URL (sdk-version 1.6.6)

### ISSUE THREAD

**Issue by da-crystal** [telerik/backend-services-js-sdk#6]
**Everlive-sdk version** 1.6.6
**Platform:** iOS simulator  (iPhone 6 / iOS 9.2 (13C75))

Invoking the following snippet using sdk version 1.6.6 on  iOS simulator  (iPhone 6 / iOS 9.2 ) :
```javascript
var everlive = new Everlive({ appId:"REMOVED APPID", scheme:"https"});
everlive.date("{CONTENTTYPE_NAME}").get(null)
```

Will error out with:
`Error: unsupported URL`

However, testing the same sdk-version(1.6.6) with the following platforms are successful:

- Desktop Chrome browser - MacOS
- Android Device (lollipop)
 
#### My current workaround
Downgrade the library to version 1.6.5 as it worked with the above mentioned platforms.

**Comment by AntonDobrev** [comment]
@da-crystal Thanks for your report. We identified such issue when the SDK is used in telerik/nativescript environment. It will be fixed with the next release of the SDK. 

Can you please confirm this is the case on your side?

**Comment by AntonDobrev** [comment]
@da-crystal should be fixed in 1.6.7

**Comment by Daxito** [comment]
This is still an issue with version 1.7.0, the latest one....
